version: "3.3"

services:
  win:
    image: avinashdesireddy/iis-dotnetcore:nowinauth
    ports:
    - "81:80"
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: "demoapp.swarm.cluster.avinashdesireddy.com"
        com.docker.lb.network: demoapp
        com.docker.lb.port: 8080
    networks:
      - demoapp

networks:
  demoapp:
    external:
      name: demoapp
